Algoritmo "ex06"
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler a base e a altura de um retângulo e calcular a área (base * altura)
// Autor(a)    : Matheus Coletti
Var
   base: real
   altura: real
   area: real

Inicio
   escreval("Informe a base: ")
   leia(base)
   escreval("Informe a altura: ")
   leia(altura)
   
   area <- base * altura
   
   escreval("Area do retangulo: ", area)
Fimalgoritmo