Algoritmo "ex25_L"
// Professor   : Jailson Costa dos Santos
// Descricao   : Ler tres valores A, B e C e apresentar a soma dos quadrados dos tres valores.
// Autor(a)    : Matheus Coletti
Var
   a: real
   b: real
   c: real

Inicio
   escreval("Digite o valor de A: ")
   leia(a)
   escreval("Digite o valor de B: ")
   leia(b)
   escreval("Digite o valor de C: ")
   leia(c)
   escreval("Soma dos quadrados: ", (a ^ 2) + (b ^ 2) + (c ^ 2))
Fimalgoritmo