Algoritmo "ex25_I"
// Professor   : Jailson Costa dos Santos
// Descricao   : Ler dois inteiros A e B e imprimir o quadrado da diferenca do primeiro pelo segundo.
// Autor(a)    : Matheus Coletti
Var
   a: inteiro
   b: inteiro

Inicio
   escreval("Digite o valor de A: ")
   leia(a)
   escreval("Digite o valor de B: ")
   leia(b)
   escreval("Quadrado da diferenca (A - B)^2 = ", (a - b) ^ 2)
Fimalgoritmo