Algoritmo "ex25_M"
// Professor   : Jailson Costa dos Santos
// Descricao   : Ler tres valores A, B e C e apresentar o quadrado da soma dos tres valores.
// Autor(a)    : Matheus Coletti
Var
   a: real
   b: real
   c: real

Inicio
   escreval("Digite o valor de A: ")
   leia(a)
   escreval("Digite o valor de B: ")
   leia(b)
   escreval("Digite o valor de C: ")
   leia(c)
   escreval("Quadrado da soma: ", (a + b + c) ^ 2)
Fimalgoritmo